# Generated by Django 5.2.1 on 2025-05-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('laboratorio', models.CharField(max_length=255)),
                ('sintomas', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
