# Generated by Django 5.2.1 on 2025-05-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='imagen_url',
            field=models.URLField(blank=True),
        ),
    ]
