# Generated by Django 5.2.1 on 2025-05-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_medicamento_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='fuente',
            field=models.CharField(default='CruzVerde', max_length=50),
        ),
    ]
